[bell]
duration = 0

[colors.bright]
black = "#002b36"
blue = "#839496"
cyan = "#93a1a1"
green = "#586e75"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#fdf6e3"
yellow = "#657b83"

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.normal]
black = "#073642"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"

[cursor.style]
# blink_interval = 100
blinking = "Always"

[env]
TERM = "xterm-256color"

[font]
size = 20.0

[font.bold]
family = "Iosevka Nerd Font"
style = "Bold"

[font.italic]
family = "Iosevka Nerd Font"
style = "Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.offset]
y = 5

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[window]
decorations = "buttonless"
dynamic_padding = false

[window.padding]
x = 5
y = 5
