require('settings')
require('plugins')
require('colorscheme.solarized')
require('keymaps')
-- require('lsp')
require('navigator-config')
require('telescope-config')
require('cmp-nvim-config')
require('nvim-tree-config')
